name: jshint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: apt
      run: sudo apt-get install -y nodejs npm

    - name: jshint install
      run: sudo npm i -g jshint

    - name: jshint run
      run: cd static/js && jshint
